<?php

class WorkorderTableSeeder extends Seeder {

    public function run() {

		DB::table('workorders')->delete();

        Workorder::create(array(
			'id'=>1,
			'tipo_orden'=>2,
			'no_orden'=>'12345',
			'clase_trabajo'=>'TRABAJO DE PRUEBA',
			'fecha_entrega'=>'2016-00-00',
			'encuadernado'=>1,
			'tipo_encuadernado'=>1,
			'sublimaciones'=>0,
			'tipo_sublimacion'=>1,
			'sello'=>0,
			'tipo_sello'=>1,
			'gigantografia'=>0,
			'tipo_gigantografia'=>1,
			'impresiones'=>0,
			'tipo_impresiones'=>1,
			'servicio_numerado'=>0,
			'servicio_perforado'=>1,
			'servicio_repuje'=>0,
			'servicio_levante'=>1,
			'servicio_engrapado'=>0,
			'servicio_grafado'=>1,
			'servicio_laminado'=>0,
			'servicio_otro'=>'1',
			'servicio_engomado'=>0,
			'servicio_corte'=>0,
			'servicio_refile'=>1,
			'detalles_trabajo'=>'DETALLE DE PRUEBA DE TRABAJO NO 12345',
			'valor_trabajo'=>100000,
			'abono'=>40000,
			'saldo'=>60000,
			'subtotal'=>86207,
			'iva'=>2,
			'no_factura'=>12345,
			'total'=>100000,
			'vendedor'=>'ALVARO BUELVAS',
			'estado_trabajo'=>1,
			'diseñador'=>'',
			'tipo_realizado'=>1,
			'tipo_impresion'=>1,
			'plancha'=>0,
			'tipo_plancha'=>1,
			'master'=>0,
			'tipo_master'=>1,
			'no_dian'=>'',
			'fecha_dian'=>'',
			'habilitado_dian'=>'',
			'observacion_diseño'=>'',
			'fecha_reporte_diseño'=>'0000-00-00',
			'revisado_diseño'=>'',
			'autorizado_diseño'=>'',
			'maquina'=>'',
			'clase_material'=>'',
			'cantidad_trabajo'=>'',
			'tamano'=>'',
			'cantidad_material'=>'',
			'corte_material'=>'',
			'emblocado'=>'',
			'no_inicial'=>'',
			'no_final'=>'',
			'no_tintas'=>1,
			'color_tinta'=>'',
			'tinta_especial'=>'',
			'color_material'=>'',
			'no_copia'=>0,
			'copia1'=>1,
			'copia2'=>1,
			'copia3'=>1,
			'copia4'=>1,
			'numerado'=>0,
			'numeradoras'=>1,
			'original_todas'=>0,
			'original_copia'=>0,
			'tiro_retiro'=>0,
			'observacion_impresion'=>'',
			'fecha_reporte_impresion'=>'0000-00-00',
			'autorizado_impresion'=>'',
			'levante'=>0,
			'engrapado'=>0,
			'laminado'=>0,
			'plastificadouv'=>0,
			'engomado'=>0,
			'corte'=>0,
			'refile'=>0,
			'plastificadomate'=>0,
			'perforado'=>0,
			'argollado'=>0,
			'grafado'=>0,
			'plastificadoreserva'=>0,
			'empastado'=>0,
			'tapaclinto'=>0,
			'tapanormal'=>0,
			'hojassueltas'=>0,
			'otro_acabados'=>0,
			'recomendaciones'=>'',
			'observacion_acabados'=>'',
			'fecha_reporte_acabados'=>'0000-00-00',
			'autorizado_acabados'=>'',
			'customers_id'=>1
			
        ));
    }

    public function down() {
        Schema::drop('workorders');
    }
}
